package.json
src/lookupStream.js
test/lookupStreamTest.js

When the name of a place is an empty string the Document setter function get super annoyed and throws an exception. These aren't fatal, so catching them and logging to the suspect file so we can keep track of problems is good enough.

Catch exceptions from Document setter functions and log errors

---

package.json

No need to bump package version here.
Connected to pelias/api#424

Bumping pelias-model version for test dependecies only

---

.gitignore
package.json
src/httpPipResolver.js
src/localPipResolver.js
src/lookupStream.js
test/lookupStreamTest.js
test/resolversFactoryLocalTest.js
test/resolversFactoryTest.js

Add stream-end handling in order to shut down local pip child processes
Refactored the resolvers to be classes with `lookup` and `end` functions. Invoke `end` function in the parallel-stream stream-end-handler.

Add end function call to lookup processes

---

package.json
src/getAdminLayers.js
src/localPipResolver.js
src/lookupStream.js

Depends on with pelias/wof-pip-service#6, and together with it allows specifying which admin fields to look up for a given record.
Connects pelias/geonames#35

Allow configuring admin fields

---

src/getAdminLayers.js

The API label code expects that any record has admin lookup fields up to
and including the layer of the record itself. For example, regions
should have the region and region_a fields filled in by admin lookup.

Correct admin lookup layers for Geonames

---

src/getAdminLayers.js

This was missing, which would cause countries to get all admin layers.
fixes pelias/geonames#25

Add country to admin layers filtering

---

src/lookupStream.js
test/lookupStreamTest.js

No API code uses these fields any more, so we should avoid setting them
in any documents we index.

Set only new admin fields

---

src/getAdminLayers.js

Fix some issues with the choices of which layers to perform admin lookup against.
Removes borough lookup from locality, which was something we should never have added.
Fixes pelias/geonames#73 by only looking up macroregion records against macroregion.

Improve layer mapping

---

src/httpPipResolver.js
test/resolversFactoryTest.js

To avoid the overhead of reinitializing HTTP connections when using an
HTTP PIP resolver, we use an HTTP agent with connection keepAlive set to
true.
However, avoiding explicitly closing these connections uses extra
resources on the server (the server will assume the connection is open
after the resolver is done with it's work). This effect is minor but we
might as well fix it.
A more important effect of this change is that it drastically speeds up
our tests! Previously, the HTTP server we created for the tests would
wait for a full 2 minutes after the tests were done before closing the
connection and shutting down. Now that the connection is explicitly
closed by the resolver, the Node process can exit immediately after the
last test is finished! 🏇
See the HTTP …

Speed up tests by explicitly closing connections on end

---

src/getAdminLayers.js

Previously, locality records did not get looked up against localadmin, which caused missing admin info.
Conversely, localadmin records were looked up against all layers, including locality and neighbourhood, which isn't correct.
This pr is a subset of the changes from #50, with no unexpected side effects regarding abbreviations. It doesn't fix as many label issues though.

Handle localadmin layer

---

bin/units
package.json

I saw the error from https://github.com/pelias/api/pull/500 in our
Travis tests for this repo. This PR ensures the test script returns 0.

Use helper scripts to ensure unit tests pass

---

index.js
package.json
src/configValidation.js
src/httpPipResolver.js
src/localPipResolver.js
src/lookupStream.js
src/resolversFactory.js
test/configValidationTest.js
test/httpPipResolverTest.js
test/localPipResolverTest.js
test/lookupStreamTest.js
test/test.js

We should discuss this.  The tradition has been to put configValidation in the main entry point so the module can't even be loaded if the configuration is invalid, that doesn't work the same way in this module since pelias config can be passed to the individual create functions.  We should probably go with dependency injection so to the create function gets only what it needs instead of hosting the entire pelias config internally.

added config validation

---

actualTestResults.json
src/pip/index.js
test/pip/data/expectedLayerLocalizedNamesTestResults.json
test/pip/data/expectedLayerTestResults.json
test/pip/data/layerTestData.json
test/pip/testDependencyMode.js
test/pip/testLayerLookup.js
test/pip/testLayerLookupLocalizedNames.js

This is the only place we have support for the `disputed` place type.  It's not supported in the model and ends up wasting execution time in admin lookup.

removed support for `disputed` place type

---

src/lookupStream.js
test/lookupStreamTest.js

This fixes the test that's failing for @tigerlily-he 
In the event of a pipResolver error, the message (along with gid, lat, and lon) are logged and the document is not forwarded downstream.

fix test by not passing doc along in case of error

---

src/pip/components/filterOutPointRecords.js
src/pip/readStream.js
test/pip/components/filterOutPointRecordsTest.js
test/test.js

For admin lookup, point records will not contain other points or polygons, so they are unnecessary. Removing them will also speed up the load.
Fixes #118

Remove records with geometry.type = point

---

schema.js
src/localPipResolver.js
src/pip/index.js
test/localPipResolverTest.js
test/pip/index.js
test/schema.js

Fixes #157 
Introduces boolean `imports.admin.missingMetafilesAreFatal` for what to do when WOF metafiles are missing while starting.  Defaults to *false* so we'll have to enable in our configs.  /src/pip/index.js returns an error in the callback while src/localPipResolver.js throws an error which will shutdown importers.

warn and skip layers with missing WOF metafiles

---

src/remotePipResolver.js

Request module supports keep-alive connections, we can pass option `forever` to enable it.
Link to documentation: https://github.com/request/request#requestoptions-callback
Could be used instead of #169. Both are working fine, so it's more about convention.

Use Keep-Alive HTTP connection

---

src/pip/index.js

The multi-process model our admin lookup code uses has been susceptible to issues with the child processes shutting down unexpectedly for a long time.
This can happen for many reasons, some of which are:
* the child process ran out of memory, for example in #117
* the Who's on First data is missing or incomplete. This has probably caused many, many confusing cases for our users
In my testing today, the PIP service will shut down after a worker has died, but only after a request has come in that actually ends up hitting that layer. For higher, less common layers like `ocean`, this may not happen for a long time.
The importers, when using `wof-admin-lookup` locally, are in even worse shape, and will often hang indefinitely.
In either case, a worker shutting down before all other workers …

Handle PIP child_process `error` and `close` events

---

index.js
test/index.js

In some cases, such as running the PIP service itself, we don't want
wof-admin-lookup to autodetect whether to to use a remote or local PIP
service.
This allows us to keep a single `pelias.json` for an entire Pelias
deployment, with remote PIP turned on, without the PIP service
attempting to recursively connect to itself and break.

feat: Expose localPipResolver function

---

src/pip/index.js
test/pip/index.js

By default, missing meta-files is a non-fatal error condition. However, the log output was always made at the `error` level.
This change keeps the existing behavior when missing metafiles ARE fatal, and logs a message as a warning when not.

feat: Use warning log level for non-fatal error

---

src/lookupStream.js
test/lookupStreamTest.js

The pip resolver was being shut down on the Node.js stream 'finish'
event, rather than the 'end' event. The finish event is called after all
data is _read_ into the stream, but there may be some processing left to
do.
The end result was that some records could never be processed and code
using this stream would hang.

fix(lookupStream): properly use lookupStream end event

---

src/lookupStream.js

This code was logging all output to a file in addition to the console.
This isn't required and can cause the import to fail if permissions to write to the file are not set.

feat(log): disable suspect-wof-record log

---

src/pip/index.js
src/pip/worker.js
test/pip/worker.js

Each admin lookup worker generates summary information with information about the WOF hierarchy, which is passed to the main process. Currently, this information is passed by writing to a file in a temporary location.
This isn't desirable as the code may be running in a Docker container that has a read-only filesystem, and in general it's not nice to write random files anyway.
By passing the same data back in the message body of the "loaded" IPC message sent back to the main process, this temporary file can be avoided.
Presumably, this method was avoided because passing what could be many megabytes of JSON between processes in this way was scary. However, even when testing with a full planet admin lookup setup, there was no noticeable difference with this new method.
Connects …

feat(worker): pass WOF summary file in message instead of via file

---

src/pip/components/extractFields.js
test/pip/components/extractFieldsTest.js

The `wof:shortcode` properly is coming to replace the `wof:abbreviation` field.
This PR allows either field to work, with `wof:shortcode` preferred, to account for people who have not yet updated their data.
Connects https://github.com/pelias/whosonfirst/issues/398
Connects https://github.com/pelias/pelias/issues/645
Connects https://github.com/whosonfirst/whosonfirst-properties/issues/78
Connects https://github.com/pelias/whosonfirst/pull/399

feat(abbreviation): use wof:shortcode if available

---

.travis.yml
package.json

Several changes regarding CI and Node.js versions
- Support for Node.js 6 has been dropped (https://github.com/pelias/pelias/issues/752)
- Semantic-release was running (doing nothing but taking up build time) on all pull requests for no reason

CI and Node.js updates

---

package.json
src/pip/worker.js

The `temp` package was until recently used in the PIP worker code, but as of https://github.com/pelias/wof-admin-lookup/pull/231 it is no longer needed. Some references to it were missed.
`temp` is now only a dev dependency.

fix(worker): Remove legacy usage of `temp` module

---

src/pip/index.js
src/pip/worker.js
test/pip/index.js
test/pip/worker.js

As measured in #242 and suspected for a long time (see https://github.com/pelias/wof-admin-lookup/issues/156), always trusting the WOF hierarchy for every record can be problematic.
In general, these problems can be fixed, for example the notable case from a few years back where Copenhagen was listed as a city within Sweden rather than Denmark.
However, one particularly bad and common case was neighbourhood boundaries. Many neighbourhood records have geometries that were estimated using Foursquare checkin data. They often encompass a very wide area. While the parent locality of all of these neighbourhoods might be generally correct, it's often possible for large areas to be incorrectly assigned a locality, region, or even country based merely on the neighbourhood.
This PR changes the …

feat(layers): Avoid trusting the WOF hierarchy of some layers (notably neighbourhood)

---

src/pip/index.js
test/pip/index.js

https://github.com/pelias/wof-admin-lookup/pull/246 introduced a bug where a query that specified layers to search could cause the PIP service or admin lookup to crash.

fix(pip): Avoid querying non-existent layer

---

src/lookupStream.js
src/usePostalCity.js

These are non-fatal error conditions that don't necessarily represent a true problem, so warning feels like the right level.
Leaving them at the `info` level also makes it harder to visually scan for progress output from the importers.

feat(logger): Use warning for invalid value messages

---

package.json
schema.js
test/schema.js

This just keeps the output of `npm install` free of warnings

feat(deps): Move from joi to @hapi/joi

---

.travis.yml
package.json

BREAKING CHANGE: Node.js 8 is no longer supported as it will reach [end of life](https://github.com/nodejs/Release#release-schedule) at the end of 2019.
Connects https://github.com/pelias/pelias/issues/837

feat(Node.js): Drop support for Node.js 8

---

src/usePostalCity.js
test/lookupStreamPostalCityTest.js

Our postal cities code originally from https://github.com/pelias/wof-admin-lookup/pull/232 can cause multiple parent IDs to end up the same.
In practice, how this ends up working is with `borough` placetypes, where the postal cities code assigns a `borough` ID to the `locality_id` parent field.
This is problematic for two reasons:
1. It causes the resulting `locality_gid` property returned by the Pelias API to be incorrect
2. It creates incorrect labels in areas with boroughs, like NYC. An example is a label changing from `132 Dean Street, Brooklyn, New York, NY, USA` to `132 Dean Street, Brooklyn, Brooklyn, NY, USA`
This change ensures that there can't be any duplicate IDs created in this way, which should solve both the particular problem mentioned here, as well as others we might find …

fix(postalCities): Do not assign a parent that is already there

---

src/lookupStream.js
src/postalCityMap.js
src/usePostalCity.js
test/lookupStreamPostalCityTest.js

@orangejulius this is a PR to make the 'postal cities' code more generic so it can handle boroughs.

make postal cities more placetype agnostic, add tests for boroughs

---

src/usePostalCity.js
test/lookupStreamPostalCityTest.js

This protection was too conservative, and would cause many records to not benefit from postal cities data.
A new test case for one of those situations is included, which now passes with this change and https://github.com/pelias/wof-admin-lookup/pull/282
_This PR includes #282 and will be rebased once it's merged_

Revert duplicate id protection

---

.travis.yml

Travis seems to have a new feature to validate build config.
The validation for recent builds (https://travis-ci.org/pelias/wof-admin-lookup/builds/649254913/config) shows that some config options are being missed, such as semantic release, due to the new way Travis is parsing our config.
This should fix it.

chore(CI): Remove deprecated `matrix` section of Travis CI config

---

src/pip/index.js
src/pip/readStream.js

WOF database will be hosted on [geocode.earth](https://geocode.earth/data/whosonfirst), per country will be available, so the code should support per country databases too.
Now, wof admin lookup will combine all databases like `whosonfirst-data-[a-z0-9-]+\.db` that means both global and per country databases.
related: pelias/whosonfirst#460  pelias/whosonfirst#469  pelias/whosonfirst#477

Supports for multiple databases

---

src/localPipResolver.js
src/pip/index.js

bugfix for issue highlighted in https://github.com/pelias/polylines/issues/245
When the stream is `/dev/null` then there is a case for prematurely shutting down all worker nodes since they will not be required.
As the code currently stands, this case is ignored and so the workers all remain running, which hangs the process.
Since this code is likely to be removed this year I didn't invest any time in refactoring the synchronous assignment of `$this.pipService`, instead I simply exposed an interface that can enumerate the workers and kill them.

gracefully handle shutting down workers before the service has finished instantiating

---

src/localPipResolver.js

I took https://github.com/pelias/wof-admin-lookup/pull/290 for a whirl and it was evident that it needed some logging to explain why the process had exited 🤷‍♂ 
related: https://github.com/pelias/polylines/issues/245

add log messages to assist in debugging

---

package.json
schema.js
src/pip/index.js
src/pip/readStream.js
test/pip/index.js
test/pip/worker.js

BREAKING CHANGE: This implements a hard switchover to using SQLite files
for admin lookup. Using bundle files is no longer supported, and as a
result the `imports.whosonfirst.sqlite` setting is now ignored.
`wof-admin-lookup` will now behave as if that flag was always set to
true.
This PR requires https://github.com/pelias/whosonfirst/pull/498 to be merged first

Always use sqlite as data source

---

src/usePostalCity.js
test/lookupStreamPostalCityTest.js

Because we now manage postal cities replacements for both borough and locality values, we have to be a bit careful about when we replace each of them.
After investigating what looked like an error in our logic for determining the best postal cities match in
https://github.com/pelias/wof-admin-lookup/issues/288, it turns out a significant issue we were seeing in Brooklyn was actually a more subtle bug.
In short, it looks like if we replace the borough field with with a postal city value, we should _not_ replace the locality value.
Closes #288

Only change locality if borough is _not_ changed

---

src/postalCityMap.js

Hi there,
:wave: Following up on the conversations over on Gitter with @orangejulius regarding postal cities lookup for the Netherlands, I did some work for the Pelias project and would love for everyone to have a look at it and provide feedback.
OpenAddresses derives the address data from the Dutch key register _Basisadministratie Adressen en Gebouwen_, or simply _BAG_ for short. On top of addresses, it provides a link to _woonplaatsen_ or localities that are used in postal addresses. This changes creates an explicit link between the addresses from OpenAddresses and the official localities as much as these are already available in WOF.
---
Compare the outcome with the addresses as can be found at [BAG Viewer](https://bagviewer.kadaster.nl/lvbag/bag-viewer/index.html)  from the Dutch …

Nl postalcity

---

src/postalCityMap.js

since WOF imported the [NZ fire and emergency localities](https://data.linz.govt.nz/layer/104830-fire-and-emergency-nz-localities/) file to the `locality` placetype the NZ postal cities mapping is both wrong and not really required.
that LINZ dataset provides very good locality mapping across NZ, so it's unlikely that the postal cities mapping is more accurate than the result returned from PIP.
Some quick background, in NZ there was recently a bit of a shift in how localities are defined in WOF.
What 🥝 call a 'Suburb' is now a locality (previously a `neighbourhood`) and the "city proper" is now a `County` (previously a `locality`).
tl;dr the current file is broken and not really required, we *could* regenerate it but it's probably not worth it.
I would consider re-generating the NZ file …

NZ postal cities map no longer required

---

.github/workflows/push.yml
README.md
package.json

This copies the Github Actions workflow from the Pelias API project.
It brings in a few notable changes:
- Run all tests against Node.js 12, 14, and 16
- Remove MacOS build jobs (they're 10x the cost, which could hurt anyone running these on private forks)
- Update jobs to run on Ubuntu 20 (Ubuntu 16 is deprecated: https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/)
- Run docker build _after_ any NPM publish, so that versioned docker images can be built
- Remove any CircleCI config that exists (we can use Github Actions to build docker images just fine)
- Remove any lingering references to TravisCI

Update GitHub actions

---

src/pip/components/extractFields.js
test/pip/components/extractFieldsTest.js

After https://github.com/pelias/api/pull/1622, which extends the `boundary.country` API parameter to include the `dependency` placetype, we noticed that venue and address records often have a 2-character country code when they are part of a dependency.
The `boundary.country` parameter currently checks only for 3-character codes, and so the best solution is to ensure the relevant property on all records in Elasticsearch is a 3-character country code whenever possible.
This change expands on the logic for selecting an abbreviation for an admin record to be used for point in polygon lookup. Logic specific to countries is expanded to include dependencies, and some additional possible fields that might contain 3-character codes are checked.
Because the abbreviation logic is now a bit more …

Use 3-character country code for dependencies where possible

---

.jshintrc
schema.js
src/data/aliases/country-endonyms.psv
src/data/aliases/country-language-map.json
src/data/aliases/country-language-map.sql
src/data/aliases/extract-aliases.js
src/data/aliases/locality-megacity-endonyms.psv
src/lookupStream.js
src/useEndonyms.js
test/lookupStreamEndonymsTest.js
test/test.js

This PR attempts to resolve a long-standing issue in Pelias where parent properties can only be specified in English (or in the 'default language').
For example querying for a country directly works fine, you can query for `Germany`, `Deutschland` or `Allemagne` to find Germany, the search logic usually targets the 'default language' and the target language of the `User-Agent`.
The issue is when using the country name in support of another query, such as the example [10 Torstraße Germany](https://pelias.github.io/compare/#/v1/autocomplete?text=10+Torstra%C3%9Fe+Germany) which works as expected, but the query [10 Torstraße Deutschland](https://pelias.github.io/compare/#/v1/autocomplete?text=10+Torstra%C3%9Fe+Deutschland) fails.
This is really not ideal since it's very English-centric, in …

ensure parent endonyms exist for all countries and megacities

---

src/data/aliases/region-endonyms.psv
src/useEndonyms.js
test/lookupStreamEndonymsTest.js

as mentioned in https://github.com/pelias/api/issues/1629, the work in https://github.com/pelias/wof-admin-lookup/pull/314 covered country and megacity endonyms but didn't cover the `region` placetype.
I've just landed https://github.com/pelias/wof-admin-lookup/pull/316 in order to update the existing dictionaries and then added a new dictionary for the `region` placetype here.
This work requires testing as per https://github.com/pelias/wof-admin-lookup/pull/314, there is a concern that it will adversely impact the index size, although that remains to be seen.
resolves: https://github.com/pelias/api/issues/1629

endonyms: add endonyms dictionary for region placetype

---

package.json
test/index.js
test/lookupStreamEndonymsTest.js
test/lookupStreamPostalCityTest.js
test/lookupStreamTest.js
test/pip/components/extractFieldsLocalizedNameTest.js
test/pip/components/extractFieldsTest.js
test/pip/components/filterOutCitylessNeighbourhoodsTest.js
test/pip/components/filterOutHierarchylessNeighbourhoodsTest.js
test/pip/components/filterOutPointRecordsTest.js
test/pip/components/simplifyGeometryTest.js

Part of https://github.com/pelias/pelias/issues/801
Technique cribbed from https://github.com/pelias/openaddresses/pull/457
I also consolidated the test_stream function in a single place.
I ran the tests before and after this change with a fresh npm install.

move away from event-stream, replace with stream-mock 

---

src/pip/index.js

:wave: I did some awesome work for the Pelias project and would love for everyone to have a look at it and provide feedback.
---
Basically how I bumped into it: we noticed that even though there is WOF data in Azerbaijan for `region` it is not returned from PIP service in many cases:
I started digging and noticed that order of layers is important, because (as I understand) we are trying to find the lowest one first and then simply use hierarchy to resolve the rest of them. Here since `marcoregion` goes first in the list of layers + there is macroregions data for Azerbaijan we basically never return region data from this service.
After changing the order it works as expected:
Worth saying that according https://github.com/whosonfirst/whosonfirst-placetypes macroregion indeed should be > …

Change order of region/macroregion layers when doing search

---

package.json
src/postalCityMap.js

The npm package `stable` is deprecated:
> Modern JS already guarantees Array#sort() is a stable sort, so this
library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
This change uses `Array#sort()` instead.
This PR replaces #322 because I can't push to the master branch to make changes. Thx @vulpivia

Remove stable

---

README.md
index.js
package.json
schema.js
src/lookupStream.js
src/spatialPipResolver.js
src/spatialWorker.js

This early draft PR allows `wof-admin-lookup` to use [pelias/spatial](https://github.com/pelias/spatial) to perform point-in-polygon operations.
the motivation for this work is to:
1. Reduce the startup time from minutes to basically instant.
2. Reduce the memory requirement from ~10GB (for the planet) to whatever you can spare for the filesystem cache.
3. Allowing for more control over the data used for admin-lookup
some potential tradeoffs are:
1. The throughput is potentially slower, we've managed to get some orders-of-magnitude gains so far, and there is potential for future improvement here. Anecdotally, on my laptop I could get 10-11k/s for the in-memory pip-service, around 5k/s when running spatial in a single thread and around 8k/s when using worker threads.
2. The spatial …

spatial: use spatial database for PIP lookups
