pelias/wof-admin-lookup

- package.json
- src/lookupStream.js
- test/lookupStreamTest.js
This internalizes and deprecates wof-regioncode-lookup module
> Add region code lookup

- src/lookupStream.js
- test/lookupStreamTest.js
> added support for treating dependency as region if there are no regions

- package.json
- src/resolversFactory.js
- test/resolversFactoryTest.js
> Add non 200 status handling

- .travis.yml
> Add fully featured TravisCI config

- src/lookupStream.js
- test/lookupStreamTest.js
this is needed for API changes by @dianashk.  
Fixed #23
> added alpha3 as country abbreviation

- package.json
- src/getAdminLayers.js
- src/lookupStream.js
- test/lookupStreamTest.js
- test/resolversFactoryTest.js
Required for addresses in NYC.  Fixed #41
> added `borough` support

- src/lookupStream.js
Looking at #22 and Julian's first comment, I interpreted something like this to be the desired fix. Please let me know if there is something more/completely different that needs to be done.
> Add config options for suspect log

- src/lookupStream.js
This is causing an exception in the OSM importer.
> Change isUndefined to isEmpty which covers more cases

- data/regions.json
Fies pelias/pelias#509 and pelias/labels#14
> changed name of DC region to "District of Columbia"

- package.json
- src/pip/components/loadJSON.js
- test/pip/components/loadJSONTest.js
References pelias/whosonfirst#209
> made missing data file non-fatal

- src/lookupStream.js
- test/lookupStreamTest.js
Removes hacky logic that uses dependency as region where there are no regions.  Fixes pelias/pelias#572.
> added support for dependencies and macrohoods

- package.json
> chore(package): update pelias-model to version 4.10.1

- package.json
> fix(package): update pelias-whosonfirst to version 2.16.3

- package.json
> fix(package): update pelias-whosonfirst to version 2.18.0

- package.json
> fix(package): update pelias-whosonfirst to version 2.18.3

- package.json
> fix(package): update pelias-whosonfirst to version 2.19.3

- package.json
> fix(package): update pelias-whosonfirst to version 2.19.9

- .gitignore
- index.js
- package.json
- src/localPipResolver.js
- src/pip/components/extractFields.js
- src/pip/components/filterOutCitylessNeighbourhoods.js
- src/pip/components/filterOutHierarchylessNeighbourhoods.js
- src/pip/index.js
- src/pip/readStream.js
- src/pip/worker.js
- test/index.js
- test/localPipResolverTest.js
- test/pip/components/extractFieldsLocalizedNameTest.js
- test/pip/components/extractFieldsTest.js
- test/pip/components/filterOutCitylessNeighbourhoodsTest.js
- test/pip/components/filterOutHierarchylessNeighbourhoodsTest.js
- test/pip/index.js
- test/pip/worker.js
- test/test.js
Testing ground for refactoring to increase performance.  
I ran the entire CA OA import on my laptop:
- prod wof-admin-lookup: 5441s (~90 minutes)
- this PR: 3170s (~52 minutes)
Fixes pelias/pelias#633
> Refactor for layer fallbacks

- index.js
- package.json
- src/remotePipResolver.js
- src/service/PointInPolygon.js
- test/index.js
- test/remotePipResolverTest.js
- test/service/PointInPolygon.js
- test/test.js
This gives us:
* consistent logging
* retry/timeout support
* as of https://github.com/pelias/microservice-wrapper/pull/14, HTTP keep-alive support
> Use microservice-wrapper for PIP requests

- package.json
> chore(package): update pelias-model to version 5.3.2

- package.json
> fix(package): update pelias-whosonfirst to version 2.22.0

- package.json
> fix(package): update pelias-whosonfirst to version 2.22.2

- src/pip/index.js
Should clean responseQueue when responseCallback is used
> [Fix] Should clean responseQueue when responseCallback is used

- package.json
> chore(package): update pelias-model to version 5.5.1

- src/pip/index.js
- src/pip/worker.js
- test/pip/index.js
- test/pip/worker.js
The format of whosonfirst filenames were recently changed.
Connects https://github.com/pelias/whosonfirst/issues/388
> fix(pip): Update WOF filenames and tests

- package.json
- schema.js
- src/pip/index.js
- src/pip/readStream.js
- src/pip/worker.js
- test/pip/index.js
Don't forget to update package.json when https://github.com/pelias/whosonfirst/pull/417 is merged and released.
>  Supports for WOF SQLite database

- test/remotePipResolverTest.js
While working on https://github.com/pelias/wof-admin-lookup/pull/267 I identified some easy improvements to make to some tests to make them easier to read and more resilient. Here they are!
> Test improvements

- src/data/aliases/country-endonyms.psv
- src/data/aliases/country-language-map.sql
- src/data/aliases/extract-aliases.js
- src/data/aliases/locality-megacity-endonyms.psv
This PR is a refresh of the dictionaries created in https://github.com/pelias/wof-admin-lookup/pull/314 with data from the latest WOF releases.
note: I sorted the old dictionaries using `sort -n` to make the diff cleaner, so the first commit is just noise.
> endonym dictionary updates

- .github/workflows/_test.yml
- package.json
This brings in support for Node.js 22
https://github.com/pelias/pelias/issues/950
> Update to pelias-whosonfirst v7.2.0

- src/pip/index.js
:wave: I did some awesome work for the Pelias project and would love for everyone to have a look at it and provide feedback.
---
- https://github.com/pelias/whosonfirst/issues/555
- https://github.com/pelias/csv-importer/issues/104
- https://github.com/pelias/csv-importer/issues/109
If you create/download your wof data manually it is not clear that the wof-admin-lookup requires the structure `wofPath/sqlite/whosonfirst-files.db`. This leads to issues in importer repositories. 
---
Just adapted the error message to make sure that it is more clear what the error is and how to fix it.
> style: Improve error message for missing sqlite folder.
